export const USERNAME_CHANGED = "USERNAME_CHANGED";
export const USEREMAIL_CHANGED = "USEREMAIL_CHANGED";
export const EDIT_USERFNAME_CHANGED = "EDIT_USERFNAME_CHANGED";
export const EDIT_USERLNAME_CHANGED = "EDIT_USERLNAME_CHANGED";
export const EDIT_USEREMAIL_CHANGED = "EDIT_USEREMAIL_CHANGED";
export const EDIT_PHONE_CHANGED = "EDIT_PHONE_CHANGED";
export const USERFORGOTEMAIL_CHANGED = "USERFORGOTEMAIL_CHANGED";
export const USERPASSWORD_CHANGED = "USERPASSWORD_CHANGED";
export const USERCONFIRMPASSWORD_CHANGED = "USERCONFIRMPASSWORD_CHANGED";
export const USERPHONE_CHANGED = "USERPHONE_CHANGED";
export const USERTOKEN_CHANGED = "USERTOKEN_CHANGED";
export const ANXIETY_LEVEL_CHANGED = "ANXIETY_LEVEL_CHANGED";

export const USERLOGINPASSWORD_CHANGED = "USERLOGINPASSWORD_CHANGED";
export const USERLOGINEMAIL_CHANGED = "USERLOGINEMAIL_CHANGED";

export const SUBSCRIPTION_TYPE_CHANGED = "SUBSCRIPTION_TYPE_CHANGED";
export const SUBSCRIPTION_LAST_DATE_CHANGED = "SUBSCRIPTION_LAST_DATE_CHANGED";

export const CLEAR_SIGNUP_FIELD = 'CLEAR_SIGNUP_FIELD';

export const CLIENT_F_NAME = 'CLIENT_F_NAME';
export const CLIENT_L_NAME = 'CLIENT_L_NAME';
export const CLIENT_EMAIL = 'CLIENT_EMAIL';
export const CLIENT_PHONE = 'CLIENT_PHONE';
export const CLIENT_ADDRESS = 'CLIENT_ADDRESS';
export const CLIENT_NOTE = 'CLIENT_NOTE';
export const CLEAR_ADD_CLIENT_FIELD = 'CLEAR_ADD_CLIENT_FIELD';

export const STAFF_F_NAME = 'STAFF_F_NAME';
export const STAFF_L_NAME = 'STAFF_L_NAME';
export const STAFF_EMAIL = 'STAFF_EMAIL';
export const STAFF_PHONE = 'STAFF_PHONE';
export const STAFF_TYPE = 'STAFF_TYPE';
export const CLEAR_ADD_STAFF_FIELD = 'CLEAR_ADD_STAFF_FIELD';
export const STAFF_NAME = 'STAFF_NAME';
export const STAFF_ABOUT = 'STAFF_ABOUT';
export const STAFF_BUFF_TIME = 'STAFF_BUFF_TIME';
export const STAFF_LEAD_TIME = 'STAFF_LEAD_TIME';

export const DEAL_TITLE = 'DEAL_TITLE';
export const DEAL_PRICE = 'DEAL_PRICE';
export const DEAL_REAL_PRICE = 'DEAL_REAL_PRICE';
export const DEAL_COUNT = 'DEAL_COUNT';
export const DEAL_DESC = 'DEAL_DESC';
export const DEAL_DATE = 'DEAL_DATE';
export const CLEAR_ADD_DEAL_FIELD = 'CLEAR_ADD_DEAL_FIELD';

export const COMPANY_NAME = 'COMPANY_NAME';
export const COMPANY_ADDRESS = 'COMPANY_ADDRESS';
export const COMPANY_WEBSITE = 'COMPANY_WEBSITE';
export const COMPANY_PHONE = 'COMPANY_PHONE';
export const COMPANY_ABOUT = 'COMPANY_ABOUT';
export const COMPANY_LANGUAGES = 'COMPANY_LANGUAGES';
export const COMPANY_POLICY = 'COMPANY_POLICY';
export const CLEAR_COMPANY_EDIT_PROFILE_FIELD = 'CLEAR_COMPANY_EDIT_PROFILE_FIELD';

export const SERVICE_HOUR = 'SERVICE_HOUR';
export const SERVICE_MIN = 'SERVICE_MIN';
export const SERVICE_PRICE = 'SERVICE_PRICE';
export const SERVICE_DESC = 'SERVICE_DESC';
export const SERVICE_TYPE = 'SERVICE_TYPE';
export const CLEAR_ADD_SERVICE_FIELD = 'CLEAR_ADD_SERVICE_FIELD';
