const ActionTypes = {};

//for signup
export const SIGNUP_WATCHER = "SIGNUP_WATCHER";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

//for login
export const LOGIN_WATCHER = "LOGIN_WATCHER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//for forgot password
export const FORGOT_PASSWORD_WATCHER = "FORGOT_PASSWORD_WATCHER";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

//for change password
export const CHANGE_PASSWORD_WATCHER = "CHANGE_PASSWORD_WATCHER";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

//for logout
export const LOGOUT_WATCHER = "LOGOUT_WATCHER";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//for reset password
export const RESET_PASSWORD_WATCHER = "RESET_PASSWORD_WATCHER";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export default ActionTypes;
